default: fast

setup:
	mkdir -p target/openqg target/jankurai target/fast reports/releases/draft
	cargo fetch --locked

fast:
	just setup
	just fmt-check
	just core-test
	just core-doc-test
	just bench-test
	just bench-doc-test

fmt-check:
	cargo fmt --all --check

core-test:
	CARGO_TARGET_DIR=target/fast CARGO_INCREMENTAL=0 CARGO_NET_OFFLINE=true cargo nextest run -p openqg-core --locked --frozen

bench-test:
	CARGO_TARGET_DIR=target/fast CARGO_INCREMENTAL=0 CARGO_NET_OFFLINE=true cargo nextest run -p openqg-bench --locked --frozen

core-doc-test:
	CARGO_TARGET_DIR=target/fast CARGO_INCREMENTAL=0 CARGO_NET_OFFLINE=true cargo test -p openqg-core --locked --frozen --doc

bench-doc-test:
	CARGO_TARGET_DIR=target/fast CARGO_INCREMENTAL=0 CARGO_NET_OFFLINE=true cargo test -p openqg-bench --locked --frozen --doc

schema-check:
	cargo run -p openqg-bench -- schema check

schema-sync:
	cargo run -p openqg-bench -- schema sync

data-lock:
	cargo run -p openqg-bench -- data lock --output target/openqg/data/locks/data-lock.json

data-verify: data-lock
	cargo run -p openqg-bench -- data verify

data-smoke:
	cargo run -p openqg-bench -- data smoke

bench-smoke:
	cargo run -p openqg-bench -- bench run --suite benchmarks/suites/smoke.yml --theory theories/sm-gr-lcdm-mnu/manifest.yml --output target/openqg/bench-smoke/scorecard.json

bench-full:
	cargo run -p openqg-bench -- bench run --suite benchmarks/suites/full.yml --theory theories/sm-gr-lcdm-mnu/manifest.yml --output target/openqg/bench-full/scorecard.json

zyal-validate:
	cargo run -p openqg-bench -- zyal validate

zyal-jekko-preview:
	mkdir -p target/openqg/zyal
	rm -f target/openqg/zyal/jekko-preview.jsonl
	preview_root="${JEKKO_PREVIEW_ROOT:-/Users/bentaylor/code/opencode/packages/jekko}"; \
	bun_bin="$(command -v bun 2>/dev/null || true)"; \
	if [ ! -d "$preview_root" ] || [ -z "$bun_bin" ]; then \
		printf 'Generated by: openqg-bench\nRegeneration command: just zyal-jekko-preview\nDO NOT EDIT BY HAND\n\n' > target/openqg/zyal/jekko-preview.jsonl; \
		printf '{"status":"skipped","reason":"external preview root unavailable or bun missing","preview_root":"%s","tool":"bun"}\n' "$preview_root" >> target/openqg/zyal/jekko-preview.jsonl; \
	else \
		printf 'Generated by: openqg-bench\nRegeneration command: just zyal-jekko-preview\nDO NOT EDIT BY HAND\n\n' > target/openqg/zyal/jekko-preview.jsonl; \
		for file in agent/zyal/*.zyal; do \
			"$bun_bin" --cwd "$preview_root" src/index.ts daemon preview -f "$(pwd)/$file" >> target/openqg/zyal/jekko-preview.jsonl; \
		done; \
	fi

research-validate:
	cargo run -p openqg-bench -- research validate

research-dedupe-check:
	cargo run -p openqg-bench -- research dedupe-check

research-smoke-fixture:
	cargo run -p openqg-bench -- research smoke-fixture

score:
	cargo run -p openqg-bench -- score compare --scorecard target/openqg/bench-smoke/scorecard.json --json target/jankurai/repo-score.json --md target/jankurai/repo-score.md

audit-baseline:
	jankurai audit . --mode advisory --json target/jankurai/accepted-baseline.json --md target/jankurai/accepted-baseline.md

audit-ratchet:
	jankurai audit . --mode ratchet --baseline target/jankurai/accepted-baseline.json --json target/jankurai/repo-score.json --md target/jankurai/repo-score.md

security:
	bash tools/security-lane.sh

check:
	just schema-check
	just data-verify
	just bench-smoke
	just zyal-validate
	just security

release-check:
	just check
	just score
	just release-pack

ci-pr:
	bash ops/ci/pr-preflight.sh

release-pack:
	cargo run -p openqg-bench -- release pack --scorecard target/openqg/bench-smoke/scorecard.json --output reports/releases/draft
