#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
# shellcheck source=ops/ci/lib.sh
source "$repo_root/ops/ci/lib.sh"
ci::cd_root

badge_regeneration_command='bash ops/ci/jankurai.sh'

prepend_badge_header() {
  local path="$1"
  local tmp
  tmp="$(mktemp)"

  case "$path" in
    *.svg)
      {
        printf '<!-- Generated by: jankurai audit -->\n'
        printf '<!-- Regeneration command: %s -->\n' "$badge_regeneration_command"
        printf '<!-- DO NOT EDIT BY HAND -->\n\n'
        cat "$path"
      } >"$tmp"
      ;;
    *)
      {
        printf 'Generated by: jankurai audit\n'
        printf 'Regeneration command: %s\n' "$badge_regeneration_command"
        printf 'DO NOT EDIT BY HAND\n\n'
        cat "$path"
      } >"$tmp"
      ;;
  esac

  mv "$tmp" "$path"
}

mkdir -p target/openqg target/jankurai reports/releases/draft

cargo fetch --locked
cargo install --locked cargo-nextest
cargo install --locked just

export CARGO_TARGET_DIR=target/fast
export CARGO_INCREMENTAL=0
export CARGO_NET_OFFLINE=true

cargo nextest run -p openqg-core --locked --frozen
cargo test -p openqg-core --locked --frozen --doc
cargo nextest run -p openqg-bench --locked --frozen
cargo test -p openqg-bench --locked --frozen --doc
just schema-check
just data-verify
just zyal-validate
just zyal-jekko-preview
bash tools/security-lane.sh
cargo run -p openqg-bench -- bench run --suite benchmarks/suites/smoke.yml --theory theories/sm-gr-lcdm-mnu/manifest.yml --output target/openqg/bench-smoke/scorecard.json
cargo run -p openqg-bench -- score compare --scorecard target/openqg/bench-smoke/scorecard.json --json target/jankurai/repo-score.json --md target/jankurai/repo-score.md
cargo run -p openqg-bench -- release pack --scorecard target/openqg/bench-smoke/scorecard.json --output reports/releases/draft
ci::jankurai_run audit . --mode advisory --json target/jankurai/accepted-baseline.json --md target/jankurai/accepted-baseline.md
ci::jankurai_run audit . --mode ratchet --baseline target/jankurai/accepted-baseline.json --json target/jankurai/repo-score.json --md target/jankurai/repo-score.md
ci::jankurai_run audit . --json target/jankurai/current-audit.json --md target/jankurai/current-audit.md --no-score-history
prepend_badge_header agent/jankurai-badge.json
prepend_badge_header agent/jankurai-badge.svg
