//! Theorem catalog: maps the registered certificate relations to their action generators.
//!
//! Each entry proves (in the theorem-statement field) which action term generates the relation,
//! under what assumptions, and at what limit. Normal CI verifies that every relation in
//! `openqg-core::certificate::registered_relations()` appears here.
//!
//! The symbolic derivations are pre-committed formula catalog entries; live CAS (SymPy) runs
//! in a controlled release job and updates `formula_catalog_version` + `action_fingerprint` only.

use serde::{Deserialize, Serialize};

/// What kind of action term generates a relation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum ActionTermKind {
    /// Generated by a normal-DGP brane extension (BraneTerm::NormalDgp).
    NormalDgpBrane {
        /// Which quantity the relation computes (e.g. "beta_function", "geff_over_g").
        computes: String,
        /// Physical limit or regime in which the relation holds.
        limit: String,
    },
    /// Generated by a Hu-Sawicki f(R) term (ScalarTensorTerm::HuSawickiFR).
    HuSawickiFR { computes: String, limit: String },
    /// Generated by a general Horndeski G4 scalar-tensor coupling.
    HorndeskiG4 { computes: String, limit: String },
    /// Generated by a conformal/disformal dark-matter coupling (MatterCoupling::Conformal).
    ConformedDarkMatterCoupling { computes: String, limit: String },
    /// Generated by dark-scattering momentum exchange (MatterCoupling::DarkScatteringDrag).
    DarkScatteringDrag { computes: String, limit: String },
    /// Background / FLRW constraint theorem (no MG mechanism; zero rigor credit).
    BackgroundConstraint { constraint: String },
    /// Phenomenology compatibility map only: no inverse-witness action.
    /// Earns no derivation-rigor credit and cannot satisfy StructurallyGenerated.
    PhenomenologyOnly { note: String },
}

impl ActionTermKind {
    /// True when this entry carries real mechanism content (not a unit theorem or phenomonly).
    pub fn is_mechanism(&self) -> bool {
        !matches!(
            self,
            ActionTermKind::BackgroundConstraint { .. } | ActionTermKind::PhenomenologyOnly { .. }
        )
    }
}

/// One entry in the static theorem catalog.
///
/// Each entry connects a certificate-registry relation name to its algebraic generator,
/// records the theorem statement, physical assumptions, and literature references.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TheoremEntry {
    /// Name matching `certificate::registered_relations()`.
    pub relation: String,
    /// The action term that generates this relation.
    pub action_term: ActionTermKind,
    /// Human-readable theorem statement (what the compiler proves about this relation).
    pub theorem_statement: String,
    /// Physical assumptions under which the theorem holds.
    pub assumptions: Vec<String>,
    /// Literature references (author-year format).
    pub references: Vec<String>,
}

impl TheoremEntry {
    /// True when this entry is generated by a real mechanism (not phenomonly or background).
    pub fn is_mechanism(&self) -> bool {
        self.action_term.is_mechanism()
    }
}

/// Return the complete static theorem catalog for the registered relations.
///
/// Based on spec-S03 §4 "Closure and correctness suite", mapping the nine current certificate
/// relations to their algebra theorem sources.
pub fn theorem_catalog() -> Vec<TheoremEntry> {
    vec![
        TheoremEntry {
            relation: "ndgp_beta_from_omega_rc".into(),
            action_term: ActionTermKind::NormalDgpBrane {
                computes: "beta_function".into(),
                limit: "full background; normal branch".into(),
            },
            theorem_statement:
                "BraneTerm::NormalDgp{omega_rc} compiles to the normal-branch background \
                 and beta function: beta(a) = 1 + 2*H*r_c*(1 + Hdot/(3H^2)), \
                 with r_c = 1/(2H0*sqrt(omega_rc))."
                    .into(),
            assumptions: vec![
                "Normal branch (H > 0, expanding universe)".into(),
                "Subhorizon limit for linear perturbations".into(),
                "Flat FLRW background".into(),
            ],
            references: vec![
                "Dvali, Gabadadze, Porrati (2000) PLB 485:208".into(),
                "Lue, Scoccimarro, Starkman (2004) PRD 69:044005".into(),
            ],
        },
        TheoremEntry {
            relation: "ndgp_geff_over_g".into(),
            action_term: ActionTermKind::NormalDgpBrane {
                computes: "geff_over_g".into(),
                limit: "subhorizon scalar-brane-bending limit".into(),
            },
            theorem_statement:
                "Same DGP extension as ndgp_beta_from_omega_rc; in the subhorizon limit \
                 G_eff/G = 1 + 1/(3*beta(a)). Must be connected to the beta theorem, \
                 not entered independently."
                    .into(),
            assumptions: vec![
                "Connected to ndgp_beta_from_omega_rc theorem receipt".into(),
                "Subhorizon limit k >> aH".into(),
            ],
            references: vec!["Lue, Scoccimarro, Starkman (2004) PRD 69:044005".into()],
        },
        TheoremEntry {
            relation: "fr_alpha_m".into(),
            action_term: ActionTermKind::HorndeskiG4 {
                computes: "alpha_M_running".into(),
                limit: "Horndeski G4 image: G4 = M_pl^2*F(phi)/2 with phi=R".into(),
            },
            theorem_statement: "Horndeski image of G4 = M_pl^2*F(phi)/2 with F = 1+f_R; \
                 compiler theorem: alpha_M = d ln F / d ln a. \
                 For Hu-Sawicki: alpha_M depends on f_R and its time evolution."
                .into(),
            assumptions: vec![
                "Hu-Sawicki f(R): F(R) = 1 + f_R(R)".into(),
                "Jordan frame; no conformal transformation applied".into(),
                "Background field equations hold".into(),
            ],
            references: vec![
                "Bellini & Sawicki (2014) JCAP 07:050".into(),
                "Hu & Sawicki (2007) PRD 76:064004".into(),
            ],
        },
        TheoremEntry {
            relation: "fr_largescale_geff_over_g".into(),
            action_term: ActionTermKind::HuSawickiFR {
                computes: "mu_a_k".into(),
                limit: "Compton wavelength limit: m_scalaron^{-1}".into(),
            },
            theorem_statement:
                "Hu-Sawicki f(R) scalaron theorem: mu(a,k) -> 1 outside the Compton radius \
                 m_scalaron^{-1} and -> 4/3 inside it (unscreened subhorizon). \
                 Sigma remains close to 1 in the linear regime."
                    .into(),
            assumptions: vec![
                "QSA valid (k >> aH, k >> a*m_scalaron excluded from Compton radius)".into(),
                "Unscreened linear regime (thin-shell ratio < 1)".into(),
                "Hu-Sawicki parameterization with n=1".into(),
            ],
            references: vec![
                "Hu & Sawicki (2007) PRD 76:064004".into(),
                "Tsujikawa (2009) PRD 77:023507".into(),
            ],
        },
        TheoremEntry {
            relation: "coupled_de_geff_over_g".into(),
            action_term: ActionTermKind::ConformedDarkMatterCoupling {
                computes: "geff_over_g_dark_matter".into(),
                limit: "subhorizon; dark-matter species only".into(),
            },
            theorem_statement: "Matter-coupling theorem for conformally coupled dark matter: \
                 dark-matter clustering sees G_eff/G = 1 + 2*beta^2 in the subhorizon limit. \
                 Baryons remain separately labeled and see GR. \
                 Cannot feed a universal baryonic mu without a local-gravity gate."
                .into(),
            assumptions: vec![
                "Conformal coupling A(phi) for dark matter only".into(),
                "Subhorizon limit k >> aH".into(),
                "Beta = d ln A / d phi (coupling strength)".into(),
                "Baryons minimally coupled".into(),
            ],
            references: vec!["Wetterich (1995) A&A 301:321".into()],
        },
        TheoremEntry {
            relation: "dark_scattering_growth_drag".into(),
            action_term: ActionTermKind::DarkScatteringDrag {
                computes: "euler_drag_growth_friction".into(),
                limit: "matter-sector momentum exchange; not a gravity-sector mu".into(),
            },
            theorem_statement: "Matter-sector momentum-exchange theorem: the coupling action or \
                 stress-transfer ansatz compiles to an Euler drag Gamma(a) and growth \
                 friction term in the dark-matter continuity/Euler equations. \
                 This is NOT a gravity-sector mu(a,k) theorem."
                .into(),
            assumptions: vec![
                "Dark matter–dark energy momentum exchange cross-section sigma_DM_DE".into(),
                "Subhorizon growth equations with drag term".into(),
            ],
            references: vec!["Simpson et al. (2011) JCAP 06:016".into()],
        },
        TheoremEntry {
            relation: "planck_mu0_geff".into(),
            action_term: ActionTermKind::PhenomenologyOnly {
                note: "Phenomenology compatibility map only. Maps a compiled mu(a,k_ref) to the \
                     Planck-style mu0 summary if an action already generated mu. A bare mu0 does \
                     not map backward to an action and receives no derivation-rigor credit."
                    .into(),
            },
            theorem_statement:
                "mu0 parametrization is a one-parameter summary of mu(a,k), not a mechanism. \
                 It can score as a phenomenology-lane diagnostic but is StructurallyUngenerated \
                 unless a compiler action produces mu(a,k) and this is its summary."
                    .into(),
            assumptions: vec![
                "mu(a,k) already computed from an action (not asserted directly)".into(),
            ],
            references: vec!["Planck 2018 VIII (arXiv:1807.06211)".into()],
        },
        TheoremEntry {
            relation: "flat_universe_omega_lambda".into(),
            action_term: ActionTermKind::BackgroundConstraint {
                constraint: "Friedmann constraint for a spatially flat FLRW background: \
                     Omega_Lambda = 1 - Omega_m - Omega_r - ... \
                     Zero mechanism credit; pure FLRW bookkeeping."
                    .into(),
            },
            theorem_statement:
                "Flat-universe Friedmann constraint. Not a modified-gravity theorem; \
                 carries zero mechanism rigor weight."
                    .into(),
            assumptions: vec!["Spatial flatness (k=0)".into(), "FLRW metric".into()],
            references: vec![],
        },
        TheoremEntry {
            relation: "h0_from_h".into(),
            action_term: ActionTermKind::BackgroundConstraint {
                constraint: "Unit theorem: H0 = 100*h (km/s/Mpc). Not MG. \
                     Zero mechanism credit."
                    .into(),
            },
            theorem_statement:
                "Unit conversion H0 = 100*h km/s/Mpc. Not a modified-gravity theorem; \
                 carries zero mechanism rigor weight."
                    .into(),
            assumptions: vec![],
            references: vec![],
        },
    ]
}

/// Look up the theorem entry for a given relation name.
pub fn relation_theorem(relation: &str) -> Option<TheoremEntry> {
    theorem_catalog()
        .into_iter()
        .find(|e| e.relation == relation)
}

/// True when a relation has an action-level mechanism generator (not background/phenomonly).
pub fn relation_is_mechanism(relation: &str) -> bool {
    relation_theorem(relation).is_some_and(|e| e.is_mechanism())
}

/// Return the action term kind for a relation, or `None` if not in the catalog.
pub fn relation_action_term(relation: &str) -> Option<ActionTermKind> {
    relation_theorem(relation).map(|e| e.action_term)
}
