//! AlgebraReceipt: binding a theory ID to its algebra and the relations it generates.

use crate::action::AlgebraTheory;
use crate::verdict::{audit_structural_generation, check_structural_generation, StructureVerdict};
use serde::{Deserialize, Serialize};

/// A durable receipt binding a theory to the AlgebraTheory that generates its certified relations.
///
/// Stored alongside a theory's JSON. The veto cascade reads the receipt to confirm that each
/// `DerivedCertificate` relation is structurally generated (or explicitly phenomonly).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AlgebraReceipt {
    /// Theory ID this receipt covers.
    pub theory_id: String,
    /// SHA-256 fingerprint of the `AlgebraTheory` at sealing time.
    pub action_fingerprint: String,
    /// Algebra schema version that produced this receipt.
    pub schema_version: String,
    /// Relations confirmed as structurally generated by the algebra.
    pub generated_relations: Vec<String>,
    /// Relations confirmed as phenomenology-only (acceptable, no mechanism credit).
    pub phenomonly_relations: Vec<String>,
}

impl AlgebraReceipt {
    /// Build a receipt by running the structural audit for all claimed relations.
    ///
    /// Any `StructurallyUngenerated` relation causes this to return `Err(relation, reason)`.
    pub fn build(
        theory_id: &str,
        algebra: &AlgebraTheory,
        claimed_relations: &[&str],
    ) -> Result<AlgebraReceipt, Vec<(String, String)>> {
        let verdicts = audit_structural_generation(claimed_relations, Some(algebra));
        let mut failures: Vec<(String, String)> = Vec::new();
        let mut generated = Vec::new();
        let mut phenomonly = Vec::new();

        for (relation, verdict) in &verdicts {
            match verdict {
                StructureVerdict::StructurallyGenerated { .. } => generated.push(relation.clone()),
                StructureVerdict::PhenomenologyOnly { .. } => phenomonly.push(relation.clone()),
                StructureVerdict::StructurallyUngenerated { reason } => {
                    failures.push((relation.clone(), reason.clone()))
                }
                StructureVerdict::UnknownRelation => {}
            }
        }

        // Also audit non-mechanism relations in claimed_relations for phenomonly.
        for r in claimed_relations {
            let v = check_structural_generation(r, Some(algebra));
            if let StructureVerdict::PhenomenologyOnly { .. } = v {
                if !phenomonly.contains(&r.to_string()) {
                    phenomonly.push(r.to_string());
                }
            }
        }

        if !failures.is_empty() {
            return Err(failures);
        }

        Ok(AlgebraReceipt {
            theory_id: theory_id.into(),
            action_fingerprint: algebra.action_fingerprint.clone(),
            schema_version: crate::action::SCHEMA_VERSION.into(),
            generated_relations: generated,
            phenomonly_relations: phenomonly,
        })
    }

    /// Check whether a specific relation is covered by this receipt (generated or phenomonly).
    pub fn covers(&self, relation: &str) -> bool {
        self.generated_relations.iter().any(|r| r == relation)
            || self.phenomonly_relations.iter().any(|r| r == relation)
    }

    /// Check whether a specific relation is mechanism-generated (not just phenomonly).
    pub fn is_mechanism_generated(&self, relation: &str) -> bool {
        self.generated_relations.iter().any(|r| r == relation)
    }
}
