#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

mkdir -p target/jankurai/security

log_path="target/jankurai/security/lane.log"
status_path="target/jankurai/security/lane-status.txt"
report_path="target/jankurai/security/evidence.json"

if [[ -n "${GITHUB_ACTIONS:-}" || "${CI:-}" == "true" || "${CI:-}" == "1" ]]; then
  security_cmd=(jankurai security run . --strict --profile ci --out "$report_path")
else
  security_cmd=(env CI=1 cargo run -p openqg-bench -- security scan --output "$report_path")
fi

if "${security_cmd[@]}" 2>&1 | tee "$log_path"; then
  lane_status="Security lane completed"
  exit_code=0
else
  exit_code=$?
  lane_status="Security lane failed with exit code ${exit_code}"
fi

cat > "$status_path" <<EOF
Generated by: tools/security-lane.sh
Regeneration command: just security
DO NOT EDIT BY HAND

${lane_status}
Log: ${log_path}
Evidence: ${report_path}
EOF

exit "$exit_code"
